### ISSUE TITLE
path with filename

### ISSUE THREAD

**Issue by ghost** [chelm/mbtiles-server#12]
Hi,
great project!
would it be possible to serve multiple files using a path with the filename?

for example a folder like:

./my_tiles1.mbtiles
./my_tiles2.mbtiles

and serving them like:

localhost:3000/my_tiles1/z/x/y.png
localhost:3000/my_tiles2/z/x/y.png

thx!

**Comment by zxzfcsu** [comment]
how did you do it？My browser shows “Tile rendering error: Error: Tile does not exist”.Do you know why?Thanks in advance!

**Comment by ghost** [comment]
it was not possible. maybe you want to have a look to other tools. I used tilestache but it also has a small bug.
