### ISSUE TITLE
Server fails to start up - not creating an express app

### ISSUE THREAD

**Issue by ssokol** [chelm/mbtiles-server#5]
I've just installed the latest version of the mbtiles-server and it appears to be missing something. Executing it results in... nothing. From a quick glance at the code, it looks like you're not creating an express app. The port variable is unused. Any chance you're latest check-in wasn't what you expected?

**Comment by chelm** [comment]
Oh shoot. I'll get this fixed today

**Comment by chelm** [comment]
all fixed, wasn't starting the server.

04f5297bc206eebeafbad7508b39fd0b67c809b7
